### Create a new Patient Entity
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "test with billing account",
  "email": "billingAccount@gmail.com",
  "address": "123 main street",
  "dateOfBirth": "1995-09-09",
  "registeredDate": "2025-10-01"
}
